name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies (no scripts)
        run: npm install --ignore-scripts --no-audit --fund=false

      - name: Build (compile + bundle)
        run: npm run build

      - name: Verify build artifacts exist
        run: node -e "['dist/server.js','dist/http.js','dist/cli.js','dist/extension.cjs'].forEach(f=>require('fs').accessSync(f));console.log('Artifacts OK')"
